#!/usr/bin/env bash

# list of directories to format
directories=("src" "tests")

# loop over directories
for dir in "${directories[@]}"; do
  # find all .cpp and .h files in the directory and its subdirectories
  find "$dir" \( -name '*.cpp' -o -name '*.h' \) -exec clang-format -i {} \;
done

